# Generated by Django 4.1.3 on 2022-11-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.CharField(default='', max_length=100)),
                ('restreint', models.CharField(default='', max_length=100)),
                ('network', models.CharField(default='', max_length=100)),
                ('programs', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('firstName', models.CharField(default=None, max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('dateStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('workplace', models.CharField(default=None, max_length=50)),
                ('job', models.CharField(default=None, max_length=50)),
                ('refAcces', models.CharField(blank=True, max_length=50, null=True)),
                ('refOrdi', models.CharField(blank=True, max_length=50, null=True)),
                ('refPhone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordinateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinateurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcbrand', models.CharField(default='', max_length=100)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('disc', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=100)),
                ('graphicCard', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebrand', models.CharField(default='', max_length=100)),
                ('conf', models.CharField(default='', max_length=100)),
                ('operateur', models.CharField(default='', max_length=100)),
                ('internet', models.CharField(default='', max_length=100)),
                ('appel', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinateur', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('acces', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sendBy', models.CharField(max_length=100)),
                ('dateReceiver', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.BooleanField(default=False)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.employee')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.service')),
                ('typeDemande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.typedemande')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='message.service'),
        ),
    ]
